### ISSUE TITLE
Incorrect usage of `authcall` 

### ISSUE THREAD

**Issue by swetshaw** [anton-rs/3074-invokers#22]
The function signature of `authcall` in line number 58 in `Auth.sol` is incorrect.

As per current impl it accepts 8 arguments: `authcall(gasLimit, to, value, 0, add(data, 0x20), mload(data), 0, 0)` , but according to the [latest EIP 3074](https://eips.ethereum.org/EIPS/eip-3074#authcall-0xf7) - it should accept 7 arguments. `valueExt` has been removed. 

Recommend using @enitrat 's fork of the patched forge , solidity and revm that has the most updated implementation 

[Foundry](https://github.com/enitrat/foundry/tree/cl/eip-3074)
[Solidity](https://github.com/enitrat/solidity/tree/cl/eip-3074)
[Revm](https://github.com/enitrat/revm/tree/cl/eip-3074)

**Comment by jxom** [comment]
Thanks! I can update my revm fork for this.

**Comment by enitrat** [comment]
Hey @jxom ! I have [revm fork](https://github.com/enitrat/revm/tree/cl/eip-3074) where I modified authcall to take 7 args only and auth to take into account the nonce when re-building the message signed. I'm not super familiar with revm so it's a bit hacky but that should work :)

**Comment by jxom** [comment]
Great! I can create a PR to include that change soon, and we could probably use that solidity fork you have for now too. :)

**Comment by jxom** [comment]
Opened a PR at #23 to resolve. @enitrat - added you as a co-author to credit for the patches.
